In [11]:
# preliminaries to invoke SciPy linear algebra functions 
from scipy import linalg as LA
# and NumPy which is used to define pi, sqrt, array, .transpose etc.
import numpy as np
#%%
#

In [12]:
# FOR PART A

In [13]:
parta = 5
alphas = np.array([33.865, 5.09479,1.15879,0.32584,0.1027410])

def Hkla(k,l):
    Ttop =3*((alphas[k]*alphas[l]))*np.sqrt(np.pi)*4*np.pi  
    T_bottom = 4*((alphas[k]+alphas[l])**(5/2))
    kinetic = Ttop/T_bottom
    Vtop = -1*4*np.pi
    V_bottom = 2*(alphas[k]+alphas[l])
    potential = Vtop/V_bottom
    Hamiltonian  = kinetic+potential
    return Hamiltonian

# define a function with a (symmetric) but otherwise
# similarly random formula for ovelap  matrix elements 
def Skla(k,l):
    top = np.pi*4*((np.sqrt(np.pi)))
    bottom = 4*((alphas[k]+alphas[l])**(3/2))
    return top/bottom

def EnergyStatesa (dimentions,the_alphas):

    Hama = np.identity(dimentions)
    Smata = np.identity(dimentions)
    for k in range(dimentions):
        for l in range(dimentions):
            Hama[k,l] = Hkla(k,l)
            Smata[k,l] = Skla(k,l)
                
    return LA.eigvalsh(Hama,Smata)

In [24]:
calculated_hydrogen = EnergyStatesa (5,alphas)
calculated_hydrogen

array([-4.99809815e-01,  2.28336366e-02,  1.49159796e+00,  8.95840331e+00,
        6.06133586e+01])

In [27]:
calculated_value = calculated_hydrogen[0]
calculated_value
exact_value = -0.5
percent_error = ((exact_value-calculated_value)/exact_value)*100
percent_error

0.038036945338604244

In [148]:
alphasb = []
for i in np.arange(0,21):
    alphasb.append(200/(2.5**i))

In [149]:
partb = np.arange(10,21)

def Hklb(k,l):
    Ttop =3*((alphasb[k]*alphasb[l]))*np.sqrt(np.pi)*4*np.pi  
    T_bottom = 4*((alphasb[k]+alphasb[l])**(5/2))
    kinetic = Ttop/T_bottom
    Vtop = -1*4*np.pi
    V_bottom = 2*(alphasb[k]+alphasb[l])
    potential = Vtop/V_bottom
    Hamiltonian  = kinetic+potential
    return Hamiltonian

# define a function with a (symmetric) but otherwise
# similarly random formula for ovelap  matrix elements 
def Sklb(k,l):
    top = np.pi*4*((np.sqrt(np.pi)))
    bottom = 4*((alphasb[k]+alphasb[l])**(3/2))
    return top/bottom

def EnergyStatesb(dimentions,the_alphas):

    Hamb = np.identity(dimentions)
    Smatb = np.identity(dimentions)
    for k in range(dimentions):
        for l in range(dimentions):
            Hamb[k,l] = Hklb(k,l)
            Smatb[k,l] = Sklb(k,l)
                
    return LA.eigvalsh(Hamb,Smatb)

In [150]:
the_dimensions = np.arange(10,21)

In [151]:
fromdimention10to20 = []
for i in np.arange(10,21):
    fromdimention10to20.append(EnergyStatesb((i),alphasb[0:i]))

In [152]:
fromdimention10to20[0:5]

[array([-4.99991632e-01, -1.04462525e-01,  2.72672692e-01,  1.43827902e+00,
         4.71446110e+00,  1.34740424e+01,  3.63579112e+01,  9.55267229e+01,
         2.51229344e+02,  6.86620498e+02]),
 array([-4.99991782e-01, -1.24780694e-01, -4.97769592e-03,  3.60013484e-01,
         1.51609363e+00,  4.78512380e+00,  1.35395588e+01,  3.64194380e+01,
         9.55849002e+01,  2.51284539e+02,  6.86672770e+02]),
 array([-4.99991794e-01, -1.24995381e-01, -5.39628868e-02,  3.55284891e-02,
         3.94309016e-01,  1.54606070e+00,  4.81221236e+00,  1.35646406e+01,
         3.64429823e+01,  9.56071598e+01,  2.51305656e+02,  6.86692768e+02]),
 array([-4.99991795e-01, -1.24995814e-01, -5.55072779e-02, -2.90121571e-02,
         5.16770012e-02,  4.07529578e-01,  1.55754759e+00,  4.82258224e+00,
         1.35742383e+01,  3.64519906e+01,  9.56156762e+01,  2.51313736e+02,
         6.86700420e+02]),
 array([-4.99991796e-01, -1.24995826e-01, -5.55316009e-02, -3.10232400e-02,
        -1.83861770e-02,  5.79

In [153]:
calculated_hydrogen

array([-4.99809815e-01,  2.28336366e-02,  1.49159796e+00,  8.95840331e+00,
        6.06133586e+01])

In [154]:
[item[0:5] for item in fromdimention10to20]

[array([-0.49999163, -0.10446253,  0.27267269,  1.43827902,  4.7144611 ]),
 array([-0.49999178, -0.12478069, -0.0049777 ,  0.36001348,  1.51609363]),
 array([-0.49999179, -0.12499538, -0.05396289,  0.03552849,  0.39430902]),
 array([-0.4999918 , -0.12499581, -0.05550728, -0.02901216,  0.051677  ]),
 array([-0.4999918 , -0.12499583, -0.0555316 , -0.03102324, -0.01838618]),
 array([-0.4999918 , -0.12499583, -0.05553723, -0.03110563, -0.01949366]),
 array([-0.4999918 , -0.12499583, -0.055539  , -0.03112756, -0.01961313]),
 array([-0.4999918 , -0.12499583, -0.05553963, -0.03113495, -0.01964856]),
 array([-0.4999918 , -0.12499583, -0.05553986, -0.03113765, -0.01966101]),
 array([-0.4999918 , -0.12499583, -0.05553995, -0.03113866, -0.01966563]),
 array([-0.4999918 , -0.12499583, -0.05553999, -0.03113905, -0.01966738])]